apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: goapp
  name: goapp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: goapp
  template:
    metadata:
      labels:
        run: goapp
    spec:
      containers:
        - image: gcr.io/kube-assimilate/goapp:latest
          name: goapp
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "10Mi"
              cpu: "100m"
